### PR TITLE
Nuget and obsolete methods updates

### PR DESCRIPTION
**Pull request by yurkinh**
Hello,
I have updated Xamarin.Forms and other nugets to latest versions. Also I have updated obsolete methods (according to Xamarin.Forms v2.5.x)

### CODE REVIEW

**Comment by raboud** [comment]
is the package now .NetStandard 2.0 compliant so we don't get warnings?

**Comment by yurkinh** [comment]
No yet. I have just updated packages. But I think I will update it to .NET Standard 2.0 with next pull request

**Comment by raboud** [comment]
you probably should roll the version number in nuspec file and add a revision note

I've been playing with the .NetStandard 2 thing not all that fun.

**Comment by yurkinh** [comment]
Updated nuspec file

**Comment by raboud** [comment]
@yurkinh thanks for doing this. Just a couple of comments you didn't have to change all those internal methods to public. In the previous version the assembly was marked internal the other assemblies.

I actually did all this in my fork. I didn't PR my change since you were in the middle of yours.

see https://github.com/raboud/SlideOverKit

**Comment by yurkinh** [comment]
It's ok. Now it would be good to merge everything.

**Comment by jessejiang0214** [comment]
Any reason to add MyView.xaml into sample project?

**Comment by yurkinh** [comment]
No. It should be deleted during merge. I forgot that I have added it to sample project.

**Comment by jessejiang0214** [comment]
@yurkinh can you delete some unused file? Thanks

**Comment by yurkinh** [comment]
Sure. I will delete them recommit changes

**Comment by jessejiang0214** [comment]
@yurkinh Thanks for your contribution.

**Comment by raboud** [comment]
does this mean the nuget package is getting updated also?

**Comment by raboud** [comment]
@jessejiang0214 @rid00z  are we going to get a new release and a nuget update??????

**Pull request merged**
